# Generated by Django 4.0 on 2022-01-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
