# Generated by Django 4.0 on 2022-01-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_employee_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('pin_code', models.IntegerField(max_length=6)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
